<?php

use App\Models\Catalog\Brand;
use App\Models\Catalog\Category;
use App\Models\Catalog\Product;
use App\Models\Catalog\Unit;
use App\Models\Communication\AppTranslation;
use App\Models\Communication\Language;
use App\Models\Communication\Notification;
use App\Models\Communication\SupportTicket;
use App\Models\Courier;
use App\Models\DealerProfile;
use App\Models\Field\AttendanceLog;
use App\Models\Field\DealerVisit;
use App\Models\Field\Expense;
use App\Models\Field\LeaveApplication;
use App\Models\Field\SalarySlip;
use App\Models\Field\SalesmanAsset;
use App\Models\Field\SalesmanTarget;
use App\Models\Field\TourPlan;
use App\Models\Finance\Payment;
use App\Models\Inventory\InventoryBatch;
use App\Models\InternalExpense;
use App\Models\InternalExpenseCategory;
use App\Models\InternalExpenseSubcategory;
use App\Models\Inventory\Warehouse;
use App\Models\Sales\Dispatch;
use App\Models\Sales\Invoice;
use App\Models\Sales\Order;
use App\Models\Sales\ProformaInvoice;
use App\Models\Sales\ReturnRequest;
use App\Models\Storefront\StorefrontBanner;
use App\Models\Storefront\StorefrontFooterLink;
use App\Models\Storefront\StorefrontSection;
use App\Models\Storefront\StorefrontSectionProduct;
use App\Models\Storefront\StorefrontServiceBlock;
use App\Models\User;

$active = ['1' => 'Active', '0' => 'Inactive'];
$userStatus = ['active' => 'Active', 'inactive' => 'Inactive', 'pending_approval' => 'Pending Approval'];
$orderStatus = ['salesman_review'=>'Salesman Review','admin_review'=>'Admin Review','approved'=>'Approved','packing'=>'Packing','dispatched'=>'Dispatched','delivered'=>'Delivered','cancelled'=>'Cancelled'];
$approvalStatus = ['pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected'];

return [
    'brand' => ['name' => 'Bawaskar ERP', 'short_name' => 'BERP'],
    'groups' => [
        ['label'=>'Navigation','items'=>[
            ['key'=>'dashboard-erp','label'=>'Dashboard ERP','route'=>'admin.dashboard','icon'=>'iconoir-report-columns'],
            ['key'=>'dashboard-hrms','label'=>'Dashboard HRMS','route'=>'admin.dashboard.hrms','icon'=>'iconoir-community'],
        ]],
        ['label'=>'People','id'=>'peopleMenu','icon'=>'iconoir-community','items'=>[
            ['key'=>'dealers','label'=>'Dealers','route'=>'admin.dealers.index','icon'=>'iconoir-shop'],['key'=>'customers','label'=>'Customers','route'=>'admin.customers.index','icon'=>'iconoir-user-love'],['key'=>'salesmen','label'=>'Salesmen','route'=>'admin.salesmen.index','icon'=>'iconoir-user-badge-check'],['key'=>'couriers','label'=>'Courier','route'=>'admin.couriers.index','icon'=>'iconoir-delivery-truck'],]],

        ['label'=>'Sales','id'=>'salesMenu','icon'=>'iconoir-reports','items'=>[
            ['key'=>'customer-sales','label'=>'Customer','id'=>'customerSalesMenu','icon'=>'iconoir-user','children'=>[
                ['key'=>'customer-orders','label'=>'Sale Orders','route'=>'admin.orders.index','params'=>['type'=>'customer'],'icon'=>'iconoir-cart'],
                ['key'=>'customer-proforma-invoices','label'=>'Proforma Invoices','route'=>'admin.proforma-invoices.index','params'=>['type'=>'customer'],'icon'=>'iconoir-page'],
                ['key'=>'customer-invoices','label'=>'Sale Invoices','route'=>'admin.invoices.index','params'=>['type'=>'customer'],'icon'=>'iconoir-receipt'],
                ['key'=>'customer-dispatches','label'=>'Dispatch & Delivery','route'=>'admin.dispatches.index','params'=>['type'=>'customer'],'icon'=>'iconoir-delivery-truck'],
                ['key'=>'customer-returns','label'=>'Returns & Cancellation','route'=>'admin.returns.index','params'=>['type'=>'customer'],'icon'=>'iconoir-undo-action'],
            ]],
            ['key'=>'dealer-sales','label'=>'Dealer','id'=>'dealerSalesMenu','icon'=>'iconoir-shop','children'=>[
                ['key'=>'dealer-orders','label'=>'Sale Orders','route'=>'admin.orders.index','params'=>['type'=>'dealer'],'icon'=>'iconoir-cart'],
                ['key'=>'dealer-proforma-invoices','label'=>'Proforma Invoices','route'=>'admin.proforma-invoices.index','params'=>['type'=>'dealer'],'icon'=>'iconoir-page'],
                ['key'=>'dealer-invoices','label'=>'Sale Invoices','route'=>'admin.invoices.index','params'=>['type'=>'dealer'],'icon'=>'iconoir-receipt'],
                ['key'=>'dealer-dispatches','label'=>'Dispatch & Delivery','route'=>'admin.dispatches.index','params'=>['type'=>'dealer'],'icon'=>'iconoir-delivery-truck'],
                ['key'=>'dealer-returns','label'=>'Returns & Cancellation','route'=>'admin.returns.index','params'=>['type'=>'dealer'],'icon'=>'iconoir-undo-action'],
            ]],
        ]],        ['label'=>'Products & Inventory','id'=>'productInventoryMenu','icon'=>'iconoir-box','items'=>[
            ['key'=>'products','label'=>'Products','route'=>'admin.products.index','icon'=>'iconoir-box-iso'],['key'=>'categories','label'=>'Category','route'=>'admin.categories.index','icon'=>'iconoir-list-select'],['key'=>'brands','label'=>'Brand','route'=>'admin.brands.index','icon'=>'iconoir-medal'],['key'=>'units','label'=>'Unit','route'=>'admin.units.index','icon'=>'iconoir-ruler'],['key'=>'inventory','label'=>'Stock','route'=>'admin.inventory.index','icon'=>'iconoir-package'],['key'=>'warehouses','label'=>'Warehouse','route'=>'admin.warehouses.index','icon'=>'iconoir-home-alt'],['key'=>'batches','label'=>'Batch & Expiry','route'=>'admin.batches.index','icon'=>'iconoir-calendar'],]],
        ['label'=>'Storefront','id'=>'storefrontMenu','icon'=>'iconoir-www','items'=>[
            ['key'=>'sf-bank-wallet-offers','label'=>'Row 5 - Bank & Wallet Offers','route'=>'admin.storefront-banners.index','params'=>['placement'=>'bank_offer','row_title'=>'Bank & Wallet Offers'],'icon'=>'iconoir-media-image'],
            ['key'=>'sf-strip-banner','label'=>'Row 7 - Small Strip Banner','route'=>'admin.storefront-banners.index','params'=>['placement'=>'strip_banner','row_title'=>'Small Strip Banner'],'icon'=>'iconoir-media-image'],
            ['key'=>'sf-personal-care-banner','label'=>'Row 13 - Banner Above Personal Care','route'=>'admin.storefront-banners.index','params'=>['placement'=>'footer_promo','row_title'=>'Banner Above Personal Care'],'icon'=>'iconoir-media-image'],
            ['key'=>'sf-bottom-blog','label'=>'Row 16 - Bottom Blog','route'=>'admin.storefront-sections.index','params'=>['section_key'=>'row_16_blog','row_title'=>'Bottom Blog'],'icon'=>'iconoir-page'],
        ]],        ['label'=>'Finance','id'=>'financeMenu','icon'=>'iconoir-dollar-circle','items'=>[
            ['key'=>'payments','label'=>'Payments','route'=>'admin.payments.index','icon'=>'iconoir-credit-card'],['key'=>'collections','label'=>'Collections','route'=>'admin.collections.index','icon'=>'iconoir-wallet'],['key'=>'outstanding','label'=>'Outstanding','route'=>'admin.outstanding.index','icon'=>'iconoir-graph-up'],]],
        ['label'=>'Expense','id'=>'companyExpenseMenu','icon'=>'iconoir-receive-dollars','items'=>[
            ['key'=>'internal-expenses','label'=>'Expense List','route'=>'admin.internal-expenses.index','icon'=>'iconoir-notes'],['key'=>'expense-categories','label'=>'Category List','route'=>'admin.expense-categories.index','icon'=>'iconoir-list-select'],['key'=>'expense-subcategories','label'=>'Subcategory List','route'=>'admin.expense-subcategories.index','icon'=>'iconoir-list'],]],
        ['label'=>'HRMS','items'=>[
            ['key'=>'timesheet','label'=>'Timesheet','id'=>'timesheetMenu','icon'=>'iconoir-calendar','children'=>[['key'=>'attendance','label'=>'Attendance','route'=>'admin.attendance.index','icon'=>'iconoir-check-circle'],['key'=>'leaves','label'=>'Leave','route'=>'admin.leaves.index','icon'=>'iconoir-calendar-minus'],['key'=>'bulk-attendance','label'=>'Bulk Attendance','route'=>'admin.attendance.bulk','icon'=>'iconoir-table-rows']]],['key'=>'dealer-visits','label'=>'Dealer Visits','route'=>'admin.dealer-visits.index','icon'=>'iconoir-map-pin'],['key'=>'tour-plans','label'=>'Tour Plans','route'=>'admin.tour-plans.index','icon'=>'iconoir-route'],['key'=>'expenses','label'=>'Expenses','route'=>'admin.expenses.index','icon'=>'iconoir-receive-dollars'],['key'=>'salary','label'=>'Salary & Payroll','route'=>'admin.salary.index','icon'=>'iconoir-coins'],['key'=>'targets','label'=>'Targets & Commission','route'=>'admin.targets.index','icon'=>'iconoir-target'],['key'=>'assets','label'=>'Salesman Assets','route'=>'admin.assets.index','icon'=>'iconoir-laptop'],]],
        ['label'=>'System','id'=>'systemMenu','icon'=>'iconoir-settings','items'=>[
            ['key'=>'notifications','label'=>'Notifications','route'=>'admin.notifications.index','icon'=>'iconoir-bell'],['key'=>'email-templates','label'=>'Email Templates','route'=>'admin.email-templates.index','icon'=>'iconoir-mail'],['key'=>'languages','label'=>'Languages','route'=>'admin.languages.index','icon'=>'iconoir-language'],['key'=>'translations','label'=>'Translations','route'=>'admin.translations.index','icon'=>'iconoir-language'],['key'=>'support','label'=>'Support','route'=>'admin.support.index','icon'=>'iconoir-headset-help'],['key'=>'reports','label'=>'Reports','route'=>'admin.reports.index','icon'=>'iconoir-stats-report'],]],
    ],
    'modules' => [
        'salesmen'=>[
            'label'=>'Salesmen','group'=>'People','description'=>'Company field-sales employees with email and password login.','model'=>User::class,'with'=>['salesmanProfile'],'search'=>['name','email','mobile'],'status_column'=>'status','status_options'=>$userStatus,
            'columns'=>[['key'=>'salesmanProfile.employee_code','label'=>'Employee Code'],['key'=>'name','label'=>'Name'],['key'=>'email','label'=>'Email'],['key'=>'mobile','label'=>'Mobile'],['key'=>'salesmanProfile.territory','label'=>'Territory'],['key'=>'salesmanProfile.basic_salary','label'=>'Basic Salary','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'name','label'=>'Full Name','rules'=>['required','string','max:255']],['name'=>'email','label'=>'Email','type'=>'email','rules'=>['required','email','max:255','unique:users,email,{id}']],['name'=>'mobile','label'=>'Mobile','rules'=>['nullable','string','max:20','unique:users,mobile,{id}']],['name'=>'password','label'=>'Password','type'=>'password','rules'=>['required','string','min:8'],'help'=>'Leave blank while editing to keep the existing password.'],['name'=>'employee_code','label'=>'Employee Code','rules'=>['required','string','max:50','unique:salesman_profiles,employee_code,{id}']],['name'=>'joining_date','label'=>'Joining Date','type'=>'date','rules'=>['nullable','date']],['name'=>'territory','label'=>'Territory','rules'=>['nullable','string','max:255']],['name'=>'basic_salary','label'=>'Basic Salary','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'target_amount','label'=>'Monthly Target','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'status','label'=>'Status','type'=>'select','options'=>$userStatus,'rules'=>['required','in:active,inactive']]],
        ],
        'dealers'=>[
            'label'=>'Dealers','group'=>'People','description'=>'B2B dealer registration, approval, salesman assignment, credit and outstanding.','model'=>User::class,'with'=>['dealerProfile.salesman'],'search'=>['name','email','mobile'],'status_column'=>'status','status_options'=>$userStatus,
            'columns'=>[['key'=>'dealerProfile.dealer_code','label'=>'Dealer Code'],['key'=>'dealerProfile.firm_name','label'=>'Firm'],['key'=>'name','label'=>'Contact Person'],['key'=>'mobile','label'=>'Mobile'],['key'=>'dealerProfile.salesman.name','label'=>'Salesman'],['key'=>'dealerProfile.credit_limit','label'=>'Credit Limit','type'=>'money'],['key'=>'dealerProfile.outstanding_balance','label'=>'Outstanding','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'name','label'=>'Contact Person','rules'=>['required','string','max:255']],['name'=>'email','label'=>'Email','type'=>'email','rules'=>['nullable','email','max:255','unique:users,email,{id}']],['name'=>'mobile','label'=>'Mobile','rules'=>['required','string','max:20','unique:users,mobile,{id}']],['name'=>'dealer_code','label'=>'Dealer Code','rules'=>['required','string','max:50','unique:dealer_profiles,dealer_code,{id}']],['name'=>'firm_name','label'=>'Firm Name','rules'=>['required','string','max:255']],['name'=>'gst_number','label'=>'GST Number','rules'=>['nullable','string','max:30']],['name'=>'salesman_id','label'=>'Assigned Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman','status'=>'active'],'rules'=>['nullable','exists:users,id']],['name'=>'credit_limit','label'=>'Credit Limit','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'outstanding_balance','label'=>'Outstanding Balance','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'status','label'=>'Status','type'=>'select','options'=>$userStatus,'rules'=>['required','in:active,inactive,pending_approval']]],
        ],
        'customers'=>[
            'label'=>'Customers','group'=>'People','description'=>'B2C retail customer accounts and language preferences.','model'=>User::class,'with'=>['customerProfile'],'search'=>['name','email','mobile'],'status_column'=>'status','status_options'=>$userStatus,
            'columns'=>[['key'=>'name','label'=>'Name'],['key'=>'mobile','label'=>'Mobile'],['key'=>'email','label'=>'Email'],['key'=>'customerProfile.preferred_language','label'=>'Language'],['key'=>'created_at','label'=>'Registered','type'=>'date'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'name','label'=>'Full Name','rules'=>['required','string','max:255']],['name'=>'email','label'=>'Email','type'=>'email','rules'=>['nullable','email','max:255','unique:users,email,{id}']],['name'=>'mobile','label'=>'Mobile','rules'=>['required','string','max:20','unique:users,mobile,{id}']],['name'=>'date_of_birth','label'=>'Date of Birth','type'=>'date','rules'=>['nullable','date']],['name'=>'preferred_language','label'=>'Preferred Language','type'=>'select','option_model'=>Language::class,'option_where'=>['is_active'=>1],'option_value'=>'code','option_label'=>'name','rules'=>['required','string','max:10']],['name'=>'status','label'=>'Status','type'=>'select','options'=>$userStatus,'rules'=>['required','in:active,inactive']]],
        ],
        'couriers'=>[
            'label'=>'Courier','group'=>'People','singular'=>'Courier Person','description'=>'Courier and delivery person master details.','model'=>Courier::class,'search'=>['courier_code','name','mobile','company_name','vehicle_number'],'status_column'=>'status','status_options'=>['active'=>'Active','inactive'=>'Inactive','on_leave'=>'On Leave'],
            'columns'=>[['key'=>'courier_code','label'=>'Courier Code'],['key'=>'name','label'=>'Name'],['key'=>'mobile','label'=>'Mobile'],['key'=>'company_name','label'=>'Company'],['key'=>'vehicle_type','label'=>'Vehicle'],['key'=>'vehicle_number','label'=>'Vehicle No.'],['key'=>'service_area','label'=>'Service Area'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'courier_code','label'=>'Courier Code','rules'=>['nullable','string','max:50','unique:couriers,courier_code,{id}'],'help'=>'Leave blank to auto-generate.'],['name'=>'name','label'=>'Full Name','rules'=>['required','string','max:255']],['name'=>'mobile','label'=>'Mobile','rules'=>['required','string','max:20','unique:couriers,mobile,{id}']],['name'=>'alternate_mobile','label'=>'Alternate Mobile','rules'=>['nullable','string','max:20']],['name'=>'email','label'=>'Email','type'=>'email','rules'=>['nullable','email','max:255','unique:couriers,email,{id}']],['name'=>'company_name','label'=>'Courier Company','rules'=>['nullable','string','max:255']],['name'=>'vehicle_type','label'=>'Vehicle Type','type'=>'select','options'=>['bike'=>'Bike','scooter'=>'Scooter','car'=>'Car','van'=>'Van','tempo'=>'Tempo','truck'=>'Truck','other'=>'Other'],'rules'=>['nullable','string','max:40']],['name'=>'vehicle_number','label'=>'Vehicle Number','rules'=>['nullable','string','max:50']],['name'=>'license_number','label'=>'License Number','rules'=>['nullable','string','max:80']],['name'=>'service_area','label'=>'Service Area','rules'=>['nullable','string','max:255']],['name'=>'address','label'=>'Address','type'=>'textarea','col'=>'col-12','rows'=>3,'rules'=>['nullable','string']],['name'=>'city','label'=>'City','rules'=>['nullable','string','max:255']],['name'=>'pincode','label'=>'Pincode','rules'=>['nullable','string','max:20']],['name'=>'id_proof_type','label'=>'ID Proof Type','type'=>'select','options'=>['aadhaar'=>'Aadhaar','pan'=>'PAN','driving_license'=>'Driving License','voter_id'=>'Voter ID','other'=>'Other'],'rules'=>['nullable','string','max:40']],['name'=>'id_proof_number','label'=>'ID Proof Number','rules'=>['nullable','string','max:80']],['name'=>'joining_date','label'=>'Joining Date','type'=>'date','rules'=>['nullable','date']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Active','inactive'=>'Inactive','on_leave'=>'On Leave'],'rules'=>['required','in:active,inactive,on_leave']],['name'=>'notes','label'=>'Notes','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']]],
        ],
        'categories'=>[
            'label'=>'Categories','group'=>'Catalog','model'=>Category::class,'with'=>['parent'],'search'=>['name','slug'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'name','label'=>'Name'],['key'=>'parent.name','label'=>'Parent Category'],['key'=>'slug','label'=>'Slug'],['key'=>'sort_order','label'=>'Sale Order'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'parent_id','label'=>'Parent Category','type'=>'select','option_model'=>Category::class,'rules'=>['nullable','exists:categories,id']],['name'=>'name','label'=>'Category Name','rules'=>['required','string','max:255']],['name'=>'slug','label'=>'Slug','rules'=>['nullable','string','max:255','unique:categories,slug,{id}'],'help'=>'Leave blank to generate from the name.'],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'brands'=>[
            'label'=>'Brands','group'=>'Catalog','model'=>Brand::class,'search'=>['name'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'name','label'=>'Brand'],['key'=>'products_count','label'=>'Products'],['key'=>'is_active','label'=>'Status','type'=>'boolean'],['key'=>'created_at','label'=>'Created','type'=>'date']],
            'with_count'=>['products'],'fields'=>[['name'=>'name','label'=>'Brand Name','rules'=>['required','string','max:255','unique:brands,name,{id}']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'units'=>[
            'label'=>'Units','group'=>'Catalog','singular'=>'Unit','model'=>Unit::class,'search'=>['name','short_name','unit_type'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'name','label'=>'Unit Name'],['key'=>'short_name','label'=>'Short Name'],['key'=>'unit_type','label'=>'Type'],['key'=>'decimal_precision','label'=>'Decimal'],['key'=>'products_count','label'=>'Products'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'with_count'=>['products'],'fields'=>[['name'=>'name','label'=>'Unit Name','rules'=>['required','string','max:255','unique:units,name,{id}']],['name'=>'short_name','label'=>'Short Name','rules'=>['required','string','max:30','unique:units,short_name,{id}'],'help'=>'Example: kg, ltr, pcs, pkt.'],['name'=>'unit_type','label'=>'Unit Type','type'=>'select','options'=>['weight'=>'Weight','volume'=>'Volume','quantity'=>'Quantity','length'=>'Length','other'=>'Other'],'rules'=>['required','string','max:40']],['name'=>'decimal_precision','label'=>'Decimal Precision','type'=>'number','rules'=>['required','integer','min:0','max:6']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'products'=>[
            'label'=>'Products','group'=>'Catalog','description'=>'Product master with homepage display control.','model'=>Product::class,'with'=>['category','brand','unit','images'],'search'=>['name','sku','hsn_code'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'images.0.path','label'=>'Image','type'=>'image'],['key'=>'sku','label'=>'SKU'],['key'=>'name','label'=>'Product'],['key'=>'storefront_row','label'=>'Homepage Row'],['key'=>'category.name','label'=>'Category'],['key'=>'brand.name','label'=>'Brand'],['key'=>'unit.short_name','label'=>'Unit'],['key'=>'dealer_price','label'=>'Dealer Price','type'=>'money'],['key'=>'customer_price','label'=>'Customer Price','type'=>'money'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[
                ['name'=>'name','label'=>'Product Name','rules'=>['required','string','max:255']],
                ['name'=>'storefront_row','label'=>'Storefront Row','type'=>'select','options'=>[
                    'row_1_main_banner'=>'Row 1 - Main Banner',
                    'row_2_small_banners'=>'Row 2 - Small Banners',
                    'row_4_fruits_vegetables'=>'Row 4 - Fruits & Vegetables',
                    'row_6_top_selling_items'=>'Row 6 - Top Selling Items',
                    'row_8_breakfast_dairy'=>'Row 8 - Breakfast & Dairy',
                    'row_9_chemist_store'=>'Row 9 - Chemist Store',
                    'row_10_two_banners'=>'Row 10 - Two Promo Banners',
                    'row_11_drinks'=>'Row 11 - Drinks',
                    'row_12_grocery_staples'=>'Row 12 - Grocery & Staples',
                    'row_14_personal_care'=>'Row 14 - Personal Care',
                    'row_15_kitchen_dining'=>'Row 15 - Kitchen & Dining Needs',
                ],'rules'=>['nullable','string','max:100']],
                ['name'=>'category_id','label'=>'Category','type'=>'select','option_model'=>Category::class,'rules'=>['nullable','exists:categories,id']],
                ['name'=>'brand_id','label'=>'Brand','type'=>'select','option_model'=>Brand::class,'rules'=>['nullable','exists:brands,id']],
                ['name'=>'product_type','label'=>'Product Type','type'=>'select','options'=>['medicine'=>'Medicine','veterinary'=>'Veterinary Product','fertilizer'=>'Fertilizer','seed'=>'Seed','equipment'=>'Equipment','other'=>'Other'],'rules'=>['required','string','max:40']],
                ['name'=>'unit_id','label'=>'Select Unit','type'=>'select','option_model'=>Unit::class,'option_where'=>['is_active'=>true],'rules'=>['nullable','exists:units,id']],
                ['name'=>'sku','label'=>'SKU','rules'=>['required','string','max:80','unique:products,sku,{id}']],
                ['name'=>'hsn_code','label'=>'HSN Code','rules'=>['nullable','string','max:40']],
                ['name'=>'gst_percent','label'=>'GST %','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0','max:100']],
                ['name'=>'mrp','label'=>'MRP','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],
                ['name'=>'dealer_price','label'=>'Dealer Price','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],
                ['name'=>'customer_price','label'=>'Customer Price','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],
                ['name'=>'primary_image','label'=>'Product Main Image','type'=>'image','upload_dir'=>'uploads/products','rules'=>['nullable','image','max:5120']],
                ['name'=>'description','label'=>'Description','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],
                ['name'=>'storefront_title','label'=>'Storefront Banner Title','rules'=>['nullable','string','max:255']],
                ['name'=>'storefront_subtitle','label'=>'Storefront Banner Subtitle','rules'=>['nullable','string','max:255']],
                ['name'=>'storefront_description','label'=>'Storefront Banner Description','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],
                ['name'=>'storefront_banner_image','label'=>'Storefront Banner Image','type'=>'image','upload_dir'=>'uploads/storefront/product-banners','rules'=>['nullable','image','max:5120']],
                ['name'=>'sort_order','label'=>'Storefront Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],
                ['name'=>'additional_info','label'=>'Additional Info','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],
                ['name'=>'care_instructions','label'=>'Care Instructions','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],
                ['name'=>'manufacturer_details','label'=>'Manufacturer Details','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],
                ['name'=>'offer_start_at','label'=>'Offer Start Date & Time','type'=>'datetime-local','rules'=>['nullable','date']],
                ['name'=>'offer_end_at','label'=>'Offer End Date & Time','type'=>'datetime-local','rules'=>['nullable','date','after_or_equal:offer_start_at']],
                ['name'=>'is_offer_active','label'=>'Offer Timer Active','type'=>'checkbox','rules'=>['boolean']],
                ['name'=>'is_visible_to_dealers','label'=>'Visible to Dealers','type'=>'checkbox','rules'=>['boolean']],
                ['name'=>'is_visible_to_customers','label'=>'Visible to Customers','type'=>'checkbox','rules'=>['boolean']],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']],
            ],
        ],        'pricing'=>[
            'label'=>'Dealer & Customer Pricing','group'=>'Catalog','singular'=>'Product Price','model'=>Product::class,'with'=>['category'],'search'=>['name','sku'],'can_create'=>false,'can_delete'=>false,
            'columns'=>[['key'=>'sku','label'=>'SKU'],['key'=>'name','label'=>'Product'],['key'=>'mrp','label'=>'MRP','type'=>'money'],['key'=>'dealer_price','label'=>'Dealer Price','type'=>'money'],['key'=>'customer_price','label'=>'Customer Price','type'=>'money'],['key'=>'gst_percent','label'=>'GST %']],
            'fields'=>[['name'=>'mrp','label'=>'MRP','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'dealer_price','label'=>'Dealer Price','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'customer_price','label'=>'Customer Price','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'gst_percent','label'=>'GST %','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0','max:100']]],
        ],
        'warehouses'=>[
            'label'=>'Warehouses','group'=>'Inventory','model'=>Warehouse::class,'search'=>['name','code','city'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'code','label'=>'Code'],['key'=>'name','label'=>'Warehouse'],['key'=>'city','label'=>'City'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'name','label'=>'Warehouse Name','rules'=>['required','string','max:255']],['name'=>'code','label'=>'Code','rules'=>['required','string','max:50','unique:warehouses,code,{id}']],['name'=>'city','label'=>'City','rules'=>['nullable','string','max:255']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'batches'=>[
            'label'=>'Batch & Expiry','group'=>'Inventory','singular'=>'Inventory Batch','model'=>InventoryBatch::class,'with'=>['product','warehouse'],'search'=>['batch_no'],'sort'=>['expiry_date','asc'],
            'columns'=>[['key'=>'batch_no','label'=>'Batch No.'],['key'=>'product.name','label'=>'Product'],['key'=>'warehouse.name','label'=>'Warehouse'],['key'=>'quantity','label'=>'Available Qty'],['key'=>'expiry_date','label'=>'Expiry','type'=>'date'],['key'=>'purchase_price','label'=>'Purchase Price','type'=>'money']],
            'fields'=>[['name'=>'warehouse_id','label'=>'Warehouse','type'=>'select','option_model'=>Warehouse::class,'option_where'=>['is_active'=>true],'rules'=>['required','exists:warehouses,id']],['name'=>'product_id','label'=>'Product','type'=>'select','option_model'=>Product::class,'option_where'=>['is_active'=>true],'rules'=>['required','exists:products,id']],['name'=>'batch_no','label'=>'Batch Number','rules'=>['required','string','max:100']],['name'=>'manufacturing_date','label'=>'Manufacturing Date','type'=>'date','rules'=>['nullable','date']],['name'=>'expiry_date','label'=>'Expiry Date','type'=>'date','rules'=>['nullable','date','after_or_equal:manufacturing_date']],['name'=>'purchase_price','label'=>'Purchase Price','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'quantity','label'=>'Quantity','type'=>'number','step'=>'0.001','rules'=>['required','numeric','min:0']],['name'=>'reserved_quantity','label'=>'Reserved Quantity','type'=>'number','step'=>'0.001','rules'=>['nullable','numeric','min:0']],['name'=>'low_stock_alert','label'=>'Low Stock Alert','type'=>'number','step'=>'0.001','rules'=>['nullable','numeric','min:0']]],
        ],
        'inventory'=>[
            'label'=>'Stock','group'=>'Inventory','singular'=>'Stock Record','model'=>InventoryBatch::class,'with'=>['product','warehouse'],'search'=>['batch_no'],'can_create'=>false,'can_delete'=>false,
            'columns'=>[['key'=>'product.name','label'=>'Product'],['key'=>'warehouse.name','label'=>'Warehouse'],['key'=>'batch_no','label'=>'Batch'],['key'=>'quantity','label'=>'Quantity'],['key'=>'reserved_quantity','label'=>'Reserved'],['key'=>'low_stock_alert','label'=>'Low Stock Level'],['key'=>'expiry_date','label'=>'Expiry','type'=>'date']],
            'fields'=>[['name'=>'quantity','label'=>'Current Quantity','type'=>'number','step'=>'0.001','rules'=>['required','numeric','min:0']],['name'=>'reserved_quantity','label'=>'Reserved Quantity','type'=>'number','step'=>'0.001','rules'=>['required','numeric','min:0']],['name'=>'low_stock_alert','label'=>'Low Stock Alert','type'=>'number','step'=>'0.001','rules'=>['required','numeric','min:0']]],
        ],
        'orders'=>[
            'label'=>'Sale Orders','group'=>'Sales','singular'=>'Sale Order','model'=>Order::class,'with'=>['customer','dealer.dealerProfile','salesman','invoice','proformaInvoices'],'search'=>['order_no'],'status_column'=>'status','status_options'=>$orderStatus,'filters'=>[['name'=>'type','column'=>'order_type']],'can_delete'=>false,
            'columns'=>[['key'=>'order_no','label'=>'Sale Order No.'],['key'=>'order_type','label'=>'Channel'],['key'=>'dealer.dealerProfile.firm_name','label'=>'Dealer'],['key'=>'customer.name','label'=>'Customer'],['key'=>'salesman.name','label'=>'Salesman'],['key'=>'grand_total','label'=>'Total','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'created_at','label'=>'Date','type'=>'date']],
            'fields'=>[['name'=>'order_type','label'=>'Channel','type'=>'select','query_key'=>'type','options'=>['customer'=>'Customer','dealer'=>'Dealer'],'rules'=>['required','in:customer,dealer']],['name'=>'order_no','label'=>'Sale Order Number','rules'=>['nullable','string','max:80','unique:orders,order_no,{id}'],'help'=>'Leave blank to auto-generate.'],['name'=>'customer_id','label'=>'Customer','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'customer'],'rules'=>['nullable','required_if:order_type,customer','exists:users,id']],['name'=>'dealer_id','label'=>'Dealer','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'dealer'],'rules'=>['nullable','required_if:order_type,dealer','exists:users,id']],['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['nullable','exists:users,id']],['name'=>'status','label'=>'Order Status','type'=>'select','options'=>$orderStatus,'rules'=>['required','in:'.implode(',',array_keys($orderStatus))]],['name'=>'subtotal','label'=>'Subtotal','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'gst_total','label'=>'GST Total','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'discount_total','label'=>'Discount','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'grand_total','label'=>'Grand Total','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0'],'help'=>'Leave blank to calculate from subtotal + GST - discount.'],['name'=>'notes','label'=>'Notes','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']]],
        ],
        'proforma-invoices'=>[
            'label'=>'Proforma Invoices','group'=>'Sales','singular'=>'Proforma Invoice','description'=>'Quotation-style invoice generated before sale invoice and dispatch.','model'=>ProformaInvoice::class,'with'=>['order.customer','order.dealer.dealerProfile','order.salesman'],'search'=>['proforma_no'],'status_column'=>'status','status_options'=>['draft'=>'Draft','sent'=>'Sent','accepted'=>'Accepted','converted'=>'Converted','cancelled'=>'Cancelled'],'filters'=>[['name'=>'type','relation'=>'order','column'=>'order_type']],
            'columns'=>[['key'=>'proforma_no','label'=>'Proforma No.'],['key'=>'order.order_no','label'=>'Sale Order'],['key'=>'order.dealer.dealerProfile.firm_name','label'=>'Dealer'],['key'=>'order.customer.name','label'=>'Customer'],['key'=>'proforma_date','label'=>'Date','type'=>'date'],['key'=>'valid_until','label'=>'Valid Until','type'=>'date'],['key'=>'grand_total','label'=>'Total','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'order_id','label'=>'Sale Order','type'=>'select','option_model'=>Order::class,'option_label'=>'order_no','rules'=>['required','exists:orders,id']],['name'=>'proforma_no','label'=>'Proforma Number','rules'=>['nullable','string','max:80','unique:proforma_invoices,proforma_no,{id}'],'help'=>'Leave blank to auto-generate.'],['name'=>'proforma_date','label'=>'Proforma Date','type'=>'date','rules'=>['required','date']],['name'=>'valid_until','label'=>'Valid Until','type'=>'date','rules'=>['nullable','date','after_or_equal:proforma_date']],['name'=>'subtotal','label'=>'Subtotal','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0'],'help'=>'Leave blank to copy from sale order.'],['name'=>'gst_total','label'=>'GST Total','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0'],'help'=>'Leave blank to copy from sale order.'],['name'=>'discount_total','label'=>'Discount','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0'],'help'=>'Leave blank to copy from sale order.'],['name'=>'grand_total','label'=>'Grand Total','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0'],'help'=>'Leave blank to copy from sale order.'],['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','sent'=>'Sent','accepted'=>'Accepted','converted'=>'Converted','cancelled'=>'Cancelled'],'rules'=>['required','string','max:40']],['name'=>'notes','label'=>'Notes','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']]],
        ],
        'invoices'=>[
            'label'=>'Sale Invoices','group'=>'Sales','singular'=>'Sale Invoice','model'=>Invoice::class,'with'=>['order.customer','order.dealer.dealerProfile'],'search'=>['invoice_no'],'filters'=>[['name'=>'type','relation'=>'order','column'=>'order_type']],'can_delete'=>false,
            'columns'=>[['key'=>'invoice_no','label'=>'Invoice No.'],['key'=>'order.order_no','label'=>'Sale Order'],['key'=>'order.dealer.dealerProfile.firm_name','label'=>'Dealer'],['key'=>'order.customer.name','label'=>'Customer'],['key'=>'invoice_date','label'=>'Date','type'=>'date'],['key'=>'grand_total','label'=>'Total','type'=>'money']],
            'fields'=>[['name'=>'order_id','label'=>'Sale Order','type'=>'select','option_model'=>Order::class,'option_label'=>'order_no','rules'=>['required','exists:orders,id','unique:invoices,order_id,{id}']],['name'=>'invoice_no','label'=>'Invoice Number','rules'=>['nullable','string','max:80','unique:invoices,invoice_no,{id}'],'help'=>'Leave blank to auto-generate.'],['name'=>'invoice_date','label'=>'Invoice Date','type'=>'date','rules'=>['nullable','date'],'help'=>'Leave blank to use today.'],['name'=>'grand_total','label'=>'Grand Total','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0'],'help'=>'Leave blank to copy from sale order.'],['name'=>'pdf_path','label'=>'PDF Path','rules'=>['nullable','string','max:255']]],
        ],
        'dispatches'=>[
            'label'=>'Dispatch & Delivery','group'=>'Sales','singular'=>'Dispatch','model'=>Dispatch::class,'with'=>['order'],'search'=>['dispatch_no','courier_name','tracking_no'],'status_column'=>'status','status_options'=>['packing'=>'Packing','dispatched'=>'Dispatched','in_transit'=>'In Transit','delivered'=>'Delivered','returned'=>'Returned'],'filters'=>[['name'=>'type','relation'=>'order','column'=>'order_type']],
            'columns'=>[['key'=>'dispatch_no','label'=>'Dispatch No.'],['key'=>'order.order_no','label'=>'Sale Order'],['key'=>'courier_name','label'=>'Courier'],['key'=>'tracking_no','label'=>'Tracking'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'dispatched_at','label'=>'Dispatched','type'=>'datetime']],
            'fields'=>[['name'=>'order_id','label'=>'Sale Order','type'=>'select','option_model'=>Order::class,'option_label'=>'order_no','rules'=>['required','exists:orders,id']],['name'=>'dispatch_no','label'=>'Dispatch Number','rules'=>['required','string','max:80','unique:dispatches,dispatch_no,{id}']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['packing'=>'Packing','dispatched'=>'Dispatched','in_transit'=>'In Transit','delivered'=>'Delivered','returned'=>'Returned'],'rules'=>['required','string','max:40']],['name'=>'courier_name','label'=>'Courier Name','rules'=>['nullable','string','max:255']],['name'=>'tracking_no','label'=>'Tracking Number','rules'=>['nullable','string','max:255']],['name'=>'tracking_url','label'=>'Tracking URL','type'=>'url','rules'=>['nullable','url','max:255']],['name'=>'dispatched_at','label'=>'Dispatched At','type'=>'datetime-local','rules'=>['nullable','date']],['name'=>'delivered_at','label'=>'Delivered At','type'=>'datetime-local','rules'=>['nullable','date']]],
        ],
        'returns'=>[
            'label'=>'Returns & Cancellation','group'=>'Sales','singular'=>'Return Request','model'=>ReturnRequest::class,'with'=>['order','user'],'search'=>['return_no','reason'],'status_column'=>'status','status_options'=>['requested'=>'Requested','approved'=>'Approved','rejected'=>'Rejected','received'=>'Received','refunded'=>'Refunded'],'filters'=>[['name'=>'type','relation'=>'order','column'=>'order_type']],
            'columns'=>[['key'=>'return_no','label'=>'Return No.'],['key'=>'order.order_no','label'=>'Sale Order'],['key'=>'user.name','label'=>'Requested By'],['key'=>'reason','label'=>'Reason'],['key'=>'refund_amount','label'=>'Refund','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'order_id','label'=>'Sale Order','type'=>'select','option_model'=>Order::class,'option_label'=>'order_no','rules'=>['required','exists:orders,id']],['name'=>'user_id','label'=>'Requested By','type'=>'select','option_model'=>User::class,'rules'=>['required','exists:users,id']],['name'=>'return_no','label'=>'Return Number','rules'=>['required','string','max:80','unique:return_requests,return_no,{id}']],['name'=>'reason','label'=>'Reason','type'=>'textarea','rules'=>['required','string']],['name'=>'refund_amount','label'=>'Refund Amount','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['requested'=>'Requested','approved'=>'Approved','rejected'=>'Rejected','received'=>'Received','refunded'=>'Refunded'],'rules'=>['required','string','max:40']]],
        ],
        'payments'=>[
            'label'=>'Payments','group'=>'Finance','model'=>Payment::class,'with'=>['order','payer','collector'],'search'=>['payment_no','transaction_ref'],'status_column'=>'status','status_options'=>['pending'=>'Pending','paid'=>'Paid','collected'=>'Collected','verified'=>'Verified','failed'=>'Failed','refunded'=>'Refunded'],
            'columns'=>[['key'=>'payment_no','label'=>'Payment No.'],['key'=>'order.order_no','label'=>'Sale Order'],['key'=>'payer.name','label'=>'Payer'],['key'=>'payment_mode','label'=>'Mode'],['key'=>'amount','label'=>'Amount','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'paid_at','label'=>'Paid At','type'=>'datetime']],
            'fields'=>[['name'=>'order_id','label'=>'Sale Order','type'=>'select','option_model'=>Order::class,'option_label'=>'order_no','rules'=>['nullable','exists:orders,id']],['name'=>'payer_id','label'=>'Payer','type'=>'select','option_model'=>User::class,'rules'=>['nullable','exists:users,id']],['name'=>'collected_by','label'=>'Collected By','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['nullable','exists:users,id']],['name'=>'payment_no','label'=>'Payment Number','rules'=>['required','string','max:80','unique:payments,payment_no,{id}']],['name'=>'payment_mode','label'=>'Payment Mode','type'=>'select','options'=>['cash'=>'Cash','upi'=>'UPI','bank_transfer'=>'Bank Transfer','card'=>'Card','gateway'=>'Online Gateway'],'rules'=>['required','string','max:40']],['name'=>'amount','label'=>'Amount','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0.01']],['name'=>'transaction_ref','label'=>'Transaction Reference','rules'=>['nullable','string','max:255']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['pending'=>'Pending','paid'=>'Paid','collected'=>'Collected','verified'=>'Verified','failed'=>'Failed','refunded'=>'Refunded'],'rules'=>['required','string','max:40']],['name'=>'paid_at','label'=>'Paid At','type'=>'datetime-local','rules'=>['nullable','date']]],
        ],
        'collections'=>[
            'label'=>'Collections','group'=>'Finance','singular'=>'Collection','model'=>Payment::class,'with'=>['payer','collector','order'],'search'=>['payment_no','transaction_ref'],'can_create'=>false,'can_delete'=>false,
            'columns'=>[['key'=>'payment_no','label'=>'Receipt No.'],['key'=>'payer.name','label'=>'Dealer'],['key'=>'collector.name','label'=>'Collected By'],['key'=>'amount','label'=>'Amount','type'=>'money'],['key'=>'payment_mode','label'=>'Mode'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'paid_at','label'=>'Date','type'=>'datetime']],
            'fields'=>[['name'=>'status','label'=>'Verification Status','type'=>'select','options'=>['collected'=>'Collected','verified'=>'Verified','rejected'=>'Rejected'],'rules'=>['required','string','max:40']],['name'=>'transaction_ref','label'=>'Reference','rules'=>['nullable','string','max:255']]],
        ],
        'outstanding'=>[
            'label'=>'Outstanding','group'=>'Finance','singular'=>'Dealer Outstanding','model'=>DealerProfile::class,'with'=>['user','salesman'],'can_create'=>false,'can_delete'=>false,
            'columns'=>[['key'=>'dealer_code','label'=>'Dealer Code'],['key'=>'firm_name','label'=>'Firm'],['key'=>'user.name','label'=>'Contact'],['key'=>'salesman.name','label'=>'Salesman'],['key'=>'credit_limit','label'=>'Credit Limit','type'=>'money'],['key'=>'outstanding_balance','label'=>'Outstanding','type'=>'money']],
            'fields'=>[['name'=>'credit_limit','label'=>'Credit Limit','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'outstanding_balance','label'=>'Outstanding Balance','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']]],
        ],
        'expense-categories'=>[
            'label'=>'Expense Categories','group'=>'Expense','singular'=>'Expense Category','model'=>InternalExpenseCategory::class,'with_count'=>['subcategories','expenses'],'search'=>['name','code'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'name','label'=>'Category'],['key'=>'code','label'=>'Code'],['key'=>'subcategories_count','label'=>'Subcategories'],['key'=>'expenses_count','label'=>'Expenses'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'name','label'=>'Category Name','rules'=>['required','string','max:255','unique:internal_expense_categories,name,{id}']],['name'=>'code','label'=>'Code','rules'=>['nullable','string','max:50','unique:internal_expense_categories,code,{id}']],['name'=>'description','label'=>'Description','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'expense-subcategories'=>[
            'label'=>'Expense Subcategories','group'=>'Expense','singular'=>'Expense Subcategory','model'=>InternalExpenseSubcategory::class,'with'=>['category'],'with_count'=>['expenses'],'search'=>['name','code'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'category.name','label'=>'Category'],['key'=>'name','label'=>'Subcategory'],['key'=>'code','label'=>'Code'],['key'=>'expenses_count','label'=>'Expenses'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'category_id','label'=>'Category','type'=>'select','option_model'=>InternalExpenseCategory::class,'option_where'=>['is_active'=>true],'rules'=>['required','exists:internal_expense_categories,id']],['name'=>'name','label'=>'Subcategory Name','rules'=>['required','string','max:255']],['name'=>'code','label'=>'Code','rules'=>['nullable','string','max:50']],['name'=>'description','label'=>'Description','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'internal-expenses'=>[
            'label'=>'Internal Expenses','group'=>'Expense','singular'=>'Internal Expense','model'=>InternalExpense::class,'with'=>['category','subcategory','payer'],'search'=>['expense_no','title','vendor_name','payment_mode'],'status_column'=>'status','status_options'=>['draft'=>'Draft','approved'=>'Approved','paid'=>'Paid','cancelled'=>'Cancelled'],'date_column'=>'expense_date',
            'columns'=>[['key'=>'expense_no','label'=>'Expense No.'],['key'=>'expense_date','label'=>'Date','type'=>'date'],['key'=>'category.name','label'=>'Category'],['key'=>'subcategory.name','label'=>'Subcategory'],['key'=>'title','label'=>'Title'],['key'=>'vendor_name','label'=>'Vendor'],['key'=>'payment_mode','label'=>'Payment Mode'],['key'=>'total_amount','label'=>'Amount','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'expense_no','label'=>'Expense No.','rules'=>['nullable','string','max:80','unique:internal_expenses,expense_no,{id}'],'help'=>'Leave blank to auto-generate.'],['name'=>'expense_date','label'=>'Expense Date','type'=>'date','rules'=>['required','date']],['name'=>'category_id','label'=>'Category','type'=>'select','option_model'=>InternalExpenseCategory::class,'option_where'=>['is_active'=>true],'rules'=>['nullable','exists:internal_expense_categories,id']],['name'=>'subcategory_id','label'=>'Subcategory','type'=>'select','option_model'=>InternalExpenseSubcategory::class,'option_where'=>['is_active'=>true],'rules'=>['nullable','exists:internal_expense_subcategories,id']],['name'=>'title','label'=>'Expense Title','rules'=>['required','string','max:255']],['name'=>'vendor_name','label'=>'Vendor / Party Name','rules'=>['nullable','string','max:255']],['name'=>'payment_mode','label'=>'Payment Mode','type'=>'select','options'=>['cash'=>'Cash','upi'=>'UPI','bank_transfer'=>'Bank Transfer','card'=>'Card','cheque'=>'Cheque','other'=>'Other'],'rules'=>['required','string','max:40']],['name'=>'taxable_amount','label'=>'Taxable Amount','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'gst_amount','label'=>'GST Amount','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'total_amount','label'=>'Total Amount','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'paid_by','label'=>'Paid By','type'=>'select','option_model'=>User::class,'rules'=>['nullable','exists:users,id']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','approved'=>'Approved','paid'=>'Paid','cancelled'=>'Cancelled'],'rules'=>['required','string','max:40']],['name'=>'receipt_path','label'=>'Receipt Upload','type'=>'file','upload_dir'=>'uploads/internal-expenses','rules'=>['nullable','file','max:5120']],['name'=>'notes','label'=>'Notes','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']]],
        ],
        'storefront-banners'=>[
            'label'=>'Home Banners','group'=>'Storefront','singular'=>'Home Banner','model'=>StorefrontBanner::class,'search'=>['placement','title','subtitle'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'image_path','label'=>'Image','type'=>'image'],['key'=>'placement','label'=>'Placement'],['key'=>'title','label'=>'Title'],['key'=>'subtitle','label'=>'Subtitle'],['key'=>'sort_order','label'=>'Sort Order'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'placement','label'=>'Placement','type'=>'select','options'=>['hero_main'=>'Hero Main - 1920 x 637','promo_small'=>'Small Promo Banner - 375 x 243','bank_offer'=>'Bank / Wallet Offer - 550 x 248','middle_promo'=>'Middle Promo Banner - 1383 x 375','footer_promo'=>'Footer Promo - 1383 x 520'],'rules'=>['required','string','max:80']],['name'=>'title','label'=>'Title','rules'=>['nullable','string','max:255']],['name'=>'subtitle','label'=>'Subtitle','rules'=>['nullable','string','max:255']],['name'=>'description','label'=>'Description','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],['name'=>'image_path','label'=>'Banner Image','type'=>'image','upload_dir'=>'uploads/storefront/banners','rules'=>['nullable','image','max:5120']],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'storefront-sections'=>[
            'label'=>'Home Sections','group'=>'Storefront','singular'=>'Home Section','model'=>StorefrontSection::class,'with'=>['category'],'search'=>['section_key','title','section_type','source_type'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'image_path','label'=>'Image','type'=>'image'],['key'=>'section_key','label'=>'Key'],['key'=>'title','label'=>'Title'],['key'=>'section_type','label'=>'Type'],['key'=>'source_type','label'=>'Source'],['key'=>'category.name','label'=>'Category'],['key'=>'product_limit','label'=>'Limit'],['key'=>'sort_order','label'=>'Sort Order'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'section_key','label'=>'Section Key','rules'=>['required','string','max:120','unique:storefront_sections,section_key,{id}'],'help'=>'Stable key used by the homepage. Example: fruits_vegetables.'],['name'=>'title','label'=>'Title','rules'=>['required','string','max:255']],['name'=>'subtitle','label'=>'Subtitle','rules'=>['nullable','string','max:255']],['name'=>'image_path','label'=>'Section Image','type'=>'image','upload_dir'=>'uploads/storefront/sections','rules'=>['nullable','image','max:5120']],['name'=>'section_type','label'=>'Section Type','type'=>'select','options'=>['category'=>'Category','product'=>'Product','offer'=>'Offer','service'=>'Service','footer'=>'Footer'],'rules'=>['required','string','max:40']],['name'=>'source_type','label'=>'Product Source','type'=>'select','options'=>['manual'=>'Manual Selected Products','category'=>'Products From Category','latest'=>'Latest Products','top_selling'=>'Top Selling Products','featured'=>'Featured Products'],'rules'=>['required','string','max:40']],['name'=>'category_id','label'=>'Category','type'=>'select','option_model'=>Category::class,'rules'=>['nullable','exists:categories,id']],['name'=>'product_limit','label'=>'Product Limit','type'=>'number','rules'=>['required','integer','min:1','max:100']],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'storefront-section-products'=>[
            'label'=>'Section Products','group'=>'Storefront','singular'=>'Section Product','model'=>StorefrontSectionProduct::class,'with'=>['section','product.images'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'product.images.0.path','label'=>'Image','type'=>'image'],['key'=>'section.title','label'=>'Section'],['key'=>'product.name','label'=>'Product'],['key'=>'sort_order','label'=>'Sort Order'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'section_id','label'=>'Home Section','type'=>'select','option_model'=>StorefrontSection::class,'option_label'=>'title','rules'=>['required','exists:storefront_sections,id']],['name'=>'product_id','label'=>'Product','type'=>'select','option_model'=>Product::class,'option_label'=>'name','rules'=>['required','exists:products,id']],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'storefront-service-blocks'=>[
            'label'=>'Service Blocks','group'=>'Storefront','singular'=>'Service Block','model'=>StorefrontServiceBlock::class,'search'=>['title','subtitle'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'icon_path','label'=>'Image','type'=>'image'],['key'=>'title','label'=>'Title'],['key'=>'subtitle','label'=>'Subtitle'],['key'=>'sort_order','label'=>'Sort Order'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'title','label'=>'Title','rules'=>['required','string','max:255']],['name'=>'subtitle','label'=>'Subtitle','rules'=>['nullable','string','max:255']],['name'=>'icon_path','label'=>'Icon','type'=>'image','upload_dir'=>'uploads/storefront/services','rules'=>['nullable','image','max:2048']],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'storefront-footer-links'=>[
            'label'=>'Footer Links','group'=>'Storefront','singular'=>'Footer Link','model'=>StorefrontFooterLink::class,'search'=>['link_group','title','url'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'image_path','label'=>'Image','type'=>'image'],['key'=>'link_group','label'=>'Group'],['key'=>'title','label'=>'Title'],['key'=>'url','label'=>'URL'],['key'=>'sort_order','label'=>'Sort Order'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'link_group','label'=>'Link Group','type'=>'select','options'=>['about'=>'About','useful'=>'Useful Link','categories'=>'Categories','store'=>'Store Information'],'rules'=>['required','string','max:80']],['name'=>'title','label'=>'Title','rules'=>['required','string','max:255']],['name'=>'url','label'=>'URL','rules'=>['required','string','max:255']],['name'=>'image_path','label'=>'Link Image','type'=>'image','upload_dir'=>'uploads/storefront/footer-links','rules'=>['nullable','image','max:2048']],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],        'attendance'=>[
            'label'=>'Attendance','group'=>'Salesman HRMS','singular'=>'Attendance Record','model'=>AttendanceLog::class,'with'=>['salesman'],'status_column'=>'status','status_options'=>['present'=>'Present','absent'=>'Absent','half_day'=>'Half Day','late'=>'Late','leave'=>'Leave'],'can_delete'=>false,
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'attendance_date','label'=>'Date','type'=>'date'],['key'=>'check_in_at','label'=>'Check In','type'=>'datetime'],['key'=>'check_out_at','label'=>'Check Out','type'=>'datetime'],['key'=>'working_minutes','label'=>'Minutes'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'attendance_date','label'=>'Attendance Date','type'=>'date','rules'=>['required','date']],['name'=>'check_in_at','label'=>'Check In','type'=>'datetime-local','rules'=>['nullable','date']],['name'=>'check_out_at','label'=>'Check Out','type'=>'datetime-local','rules'=>['nullable','date','after_or_equal:check_in_at']],['name'=>'working_minutes','label'=>'Working Minutes','type'=>'number','rules'=>['nullable','integer','min:0']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['present'=>'Present','absent'=>'Absent','half_day'=>'Half Day','late'=>'Late','leave'=>'Leave'],'rules'=>['required','string','max:40']]],
        ],
        'dealer-visits'=>[
            'label'=>'Dealer Visits','group'=>'Salesman HRMS','singular'=>'Dealer Visit','model'=>DealerVisit::class,'with'=>['salesman','dealer.dealerProfile'],'sort'=>['visited_at','desc'],
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'dealer.dealerProfile.firm_name','label'=>'Dealer'],['key'=>'visited_at','label'=>'Visited At','type'=>'datetime'],['key'=>'purpose','label'=>'Purpose'],['key'=>'remarks','label'=>'Remarks']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'dealer_id','label'=>'Dealer','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'dealer'],'rules'=>['required','exists:users,id']],['name'=>'visited_at','label'=>'Visited At','type'=>'datetime-local','rules'=>['required','date']],['name'=>'purpose','label'=>'Purpose','rules'=>['nullable','string','max:255']],['name'=>'remarks','label'=>'Remarks','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']]],
        ],
        'tour-plans'=>[
            'label'=>'Tour Plans','group'=>'Salesman HRMS','singular'=>'Tour Plan','model'=>TourPlan::class,'with'=>['salesman'],'status_column'=>'status','status_options'=>['planned'=>'Planned','approved'=>'Approved','completed'=>'Completed','cancelled'=>'Cancelled'],
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'plan_date','label'=>'Date','type'=>'date'],['key'=>'route_name','label'=>'Route'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'plan_date','label'=>'Plan Date','type'=>'date','rules'=>['required','date']],['name'=>'route_name','label'=>'Route Name','rules'=>['required','string','max:255']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['planned'=>'Planned','approved'=>'Approved','completed'=>'Completed','cancelled'=>'Cancelled'],'rules'=>['required','string','max:40']]],
        ],
        'expenses'=>[
            'label'=>'Expenses','group'=>'Salesman HRMS','singular'=>'Expense Claim','model'=>Expense::class,'with'=>['salesman','approver'],'status_column'=>'status','status_options'=>$approvalStatus,
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'expense_type','label'=>'Type'],['key'=>'expense_date','label'=>'Date','type'=>'date'],['key'=>'amount','label'=>'Amount','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'approver.name','label'=>'Approved By']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'expense_type','label'=>'Expense Type','type'=>'select','options'=>['travel'=>'Travel','fuel'=>'Fuel','food'=>'Food','hotel'=>'Hotel','mobile'=>'Mobile','other'=>'Other'],'rules'=>['required','string','max:40']],['name'=>'expense_date','label'=>'Expense Date','type'=>'date','rules'=>['required','date']],['name'=>'amount','label'=>'Amount','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0.01']],['name'=>'remarks','label'=>'Remarks','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],['name'=>'status','label'=>'Status','type'=>'select','options'=>$approvalStatus,'rules'=>['required','string','max:40']]],
        ],
        'leaves'=>[
            'label'=>'Leave','group'=>'Salesman HRMS','singular'=>'Leave Application','model'=>LeaveApplication::class,'with'=>['salesman','approver'],'status_column'=>'status','status_options'=>$approvalStatus,
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'leave_type','label'=>'Leave Type'],['key'=>'from_date','label'=>'From','type'=>'date'],['key'=>'to_date','label'=>'To','type'=>'date'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'approver.name','label'=>'Approved By']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'leave_type','label'=>'Leave Type','type'=>'select','options'=>['casual'=>'Casual','sick'=>'Sick','paid'=>'Paid','unpaid'=>'Unpaid','half_day'=>'Half Day'],'rules'=>['required','string','max:40']],['name'=>'from_date','label'=>'From Date','type'=>'date','rules'=>['required','date']],['name'=>'to_date','label'=>'To Date','type'=>'date','rules'=>['required','date','after_or_equal:from_date']],['name'=>'reason','label'=>'Reason','type'=>'textarea','col'=>'col-12','rules'=>['nullable','string']],['name'=>'status','label'=>'Status','type'=>'select','options'=>$approvalStatus,'rules'=>['required','string','max:40']]],
        ],
        'salary'=>[
            'label'=>'Salary & Payroll','group'=>'Salesman HRMS','singular'=>'Salary Slip','model'=>SalarySlip::class,'with'=>['salesman'],'status_column'=>'status','status_options'=>['draft'=>'Draft','approved'=>'Approved','paid'=>'Paid'],'can_create'=>false,'can_delete'=>false,
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'salary_month','label'=>'Month'],['key'=>'salary_year','label'=>'Year'],['key'=>'basic_salary','label'=>'Basic','type'=>'money'],['key'=>'incentives','label'=>'Incentive','type'=>'money'],['key'=>'deductions','label'=>'Deduction','type'=>'money'],['key'=>'net_salary','label'=>'Net Salary','type'=>'money'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'basic_salary','label'=>'Basic Salary','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'allowances','label'=>'Allowances','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'bonus','label'=>'Bonus','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'incentives','label'=>'Incentives','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'commission','label'=>'Commission','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'deductions','label'=>'Deductions','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'net_salary','label'=>'Net Salary','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','approved'=>'Approved','paid'=>'Paid'],'rules'=>['required','string','max:40']]],
        ],
        'targets'=>[
            'label'=>'Targets & Commission','group'=>'Salesman HRMS','singular'=>'Sales Target','model'=>SalesmanTarget::class,'with'=>['salesman'],
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'period_start','label'=>'From','type'=>'date'],['key'=>'period_end','label'=>'To','type'=>'date'],['key'=>'target_amount','label'=>'Target','type'=>'money'],['key'=>'achieved_amount','label'=>'Achieved','type'=>'money'],['key'=>'commission_percent','label'=>'Commission %']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'period_start','label'=>'Period Start','type'=>'date','rules'=>['required','date']],['name'=>'period_end','label'=>'Period End','type'=>'date','rules'=>['required','date','after_or_equal:period_start']],['name'=>'target_amount','label'=>'Target Amount','type'=>'number','step'=>'0.01','rules'=>['required','numeric','min:0']],['name'=>'achieved_amount','label'=>'Achieved Amount','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0']],['name'=>'commission_percent','label'=>'Commission %','type'=>'number','step'=>'0.01','rules'=>['nullable','numeric','min:0','max:100']]],
        ],
        'assets'=>[
            'label'=>'Salesman Assets','group'=>'Salesman HRMS','singular'=>'Asset','model'=>SalesmanAsset::class,'with'=>['salesman'],'status_column'=>'status','status_options'=>['issued'=>'Issued','returned'=>'Returned','lost'=>'Lost','damaged'=>'Damaged'],
            'columns'=>[['key'=>'salesman.name','label'=>'Salesman'],['key'=>'asset_type','label'=>'Type'],['key'=>'asset_name','label'=>'Asset'],['key'=>'serial_no','label'=>'Serial No.'],['key'=>'issued_on','label'=>'Issued','type'=>'date'],['key'=>'status','label'=>'Status','type'=>'status']],
            'fields'=>[['name'=>'salesman_id','label'=>'Salesman','type'=>'select','option_model'=>User::class,'option_where'=>['role'=>'salesman'],'rules'=>['required','exists:users,id']],['name'=>'asset_type','label'=>'Asset Type','type'=>'select','options'=>['mobile'=>'Mobile','laptop'=>'Laptop','sim'=>'SIM Card','vehicle'=>'Vehicle','other'=>'Other'],'rules'=>['required','string','max:40']],['name'=>'asset_name','label'=>'Asset Name','rules'=>['required','string','max:255']],['name'=>'serial_no','label'=>'Serial Number','rules'=>['nullable','string','max:255']],['name'=>'issued_on','label'=>'Issued On','type'=>'date','rules'=>['nullable','date']],['name'=>'returned_on','label'=>'Returned On','type'=>'date','rules'=>['nullable','date']],['name'=>'condition','label'=>'Condition','rules'=>['nullable','string','max:255']],['name'=>'status','label'=>'Status','type'=>'select','options'=>['issued'=>'Issued','returned'=>'Returned','lost'=>'Lost','damaged'=>'Damaged'],'rules'=>['required','string','max:40']]],
        ],
        'notifications'=>[
            'label'=>'Notifications','group'=>'System','singular'=>'Notification','model'=>Notification::class,'with'=>['user'],'search'=>['title','message'],'can_delete'=>true,
            'columns'=>[['key'=>'user.name','label'=>'Recipient'],['key'=>'channel','label'=>'Channel'],['key'=>'title','label'=>'Title'],['key'=>'message','label'=>'Message'],['key'=>'read_at','label'=>'Read At','type'=>'datetime'],['key'=>'created_at','label'=>'Sent','type'=>'datetime']],
            'fields'=>[['name'=>'user_id','label'=>'Recipient (blank for all)','type'=>'select','option_model'=>User::class,'rules'=>['nullable','exists:users,id']],['name'=>'channel','label'=>'Channel','type'=>'select','options'=>['push'=>'Push','email'=>'Email','sms'=>'SMS','whatsapp'=>'WhatsApp','in_app'=>'In App'],'rules'=>['required','string','max:40']],['name'=>'title','label'=>'Title','rules'=>['required','string','max:255']],['name'=>'message','label'=>'Message','type'=>'textarea','col'=>'col-12','rules'=>['required','string']]],
        ],
        'languages'=>[
            'label'=>'Languages','group'=>'System','singular'=>'Language','model'=>Language::class,'search'=>['code','name','native_name'],'status_column'=>'is_active','status_options'=>$active,'can_delete'=>false,
            'columns'=>[['key'=>'code','label'=>'Code'],['key'=>'name','label'=>'English Name'],['key'=>'native_name','label'=>'Native Name'],['key'=>'is_default','label'=>'Default','type'=>'boolean'],['key'=>'is_active','label'=>'Status','type'=>'boolean'],['key'=>'sort_order','label'=>'Sort']],
            'fields'=>[['name'=>'code','label'=>'Language Code','rules'=>['required','string','max:10','unique:languages,code,{id}'],'help'=>'Use stable locale keys like en, hi, mr, gu, pa, te. English remains the app fallback/default.'],['name'=>'name','label'=>'English Name','rules'=>['required','string','max:80']],['name'=>'native_name','label'=>'Native Name','rules'=>['nullable','string','max:120']],['name'=>'is_default','label'=>'Default Language','type'=>'checkbox','rules'=>['boolean'],'help'=>'Keep English as default. Only one default should be active.'],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']],['name'=>'sort_order','label'=>'Sort Order','type'=>'number','rules'=>['required','integer','min:0']]],
        ],        'translations'=>[
            'label'=>'Languages & Translations','group'=>'System','singular'=>'Translation','model'=>AppTranslation::class,'search'=>['translation_key','value','locale'],'status_column'=>'is_active','status_options'=>$active,
            'columns'=>[['key'=>'group','label'=>'Group'],['key'=>'translation_key','label'=>'Key'],['key'=>'locale','label'=>'Locale'],['key'=>'value','label'=>'Translation'],['key'=>'is_active','label'=>'Status','type'=>'boolean']],
            'fields'=>[['name'=>'group','label'=>'Group','rules'=>['required','string','max:80']],['name'=>'translation_key','label'=>'Translation Key','rules'=>['required','string','max:255']],['name'=>'locale','label'=>'Language','type'=>'select','option_model'=>Language::class,'option_where'=>['is_active'=>1],'option_value'=>'code','option_label'=>'name','rules'=>['required','string','max:10']],['name'=>'value','label'=>'Translated Text','type'=>'textarea','col'=>'col-12','rules'=>['required','string']],['name'=>'is_active','label'=>'Active','type'=>'checkbox','rules'=>['boolean']]],
        ],
        'support'=>[
            'label'=>'Support','group'=>'System','singular'=>'Support Ticket','model'=>SupportTicket::class,'with'=>['user'],'search'=>['ticket_no','subject','message'],'status_column'=>'status','status_options'=>['open'=>'Open','in_progress'=>'In Progress','resolved'=>'Resolved','closed'=>'Closed'],'can_create'=>false,'can_delete'=>false,
            'columns'=>[['key'=>'ticket_no','label'=>'Ticket'],['key'=>'user.name','label'=>'User'],['key'=>'subject','label'=>'Subject'],['key'=>'status','label'=>'Status','type'=>'status'],['key'=>'created_at','label'=>'Created','type'=>'datetime']],
            'fields'=>[['name'=>'status','label'=>'Status','type'=>'select','options'=>['open'=>'Open','in_progress'=>'In Progress','resolved'=>'Resolved','closed'=>'Closed'],'rules'=>['required','string','max:40']],['name'=>'message','label'=>'Message','type'=>'textarea','col'=>'col-12','rules'=>['required','string']]],
        ],
    ],
];

