<?php

return [
    'pages' => [
        '404',
        'about-us',
        'cart',
        'checkout',
        'contact-us',
        'faq',
        'forgot',
        'index-5',
        'login',
        'order-success',
        'order-tracking',
        'otp',
        'product-left-thumbnail',
        'search',
        'shop-left-sidebar',
        'sign-up',
        'user-dashboard',
        'wishlist',
    ],
    'product_type_labels' => [
        'medicine' => 'Medicine',
        'fertilizer' => 'Fertilizer',
        'seed' => 'Seeds',
        'seeds' => 'Seeds',
        'veterinary' => 'Veterinary Products',
        'veterinary_products' => 'Veterinary Products',
        'equipment' => 'Equipment',
        'other' => 'Other',
    ],
    'invoice_templates' => ['invoice-1', 'invoice-2', 'invoice-3'],
    'email_templates' => [
        'abandonment-email',
        'offer-template',
        'order-success',
        'reset-password',
        'welcome',
    ],
];
